-- Tabela PRO_CUSTOMER
CREATE TABLE IF NOT EXISTS PRO_CUSTOMER (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    tax_id VARCHAR(255) NOT NULL,
    UNIQUE (tax_id)
);

-- Tabela PRO_QUEUE
CREATE TABLE IF NOT EXISTS PRO_QUEUE (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    domain_id VARCHAR(255),
    version VARCHAR(255),
    type VARCHAR(255),
    name_queue VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRO_CUSTOMER_QUEUE (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    customer_id INT NOT NULL,
    queue_id INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES PRO_CUSTOMER(id),
    FOREIGN KEY (queue_id) REFERENCES PRO_QUEUE(id),
    UNIQUE (customer_id, queue_id)
);